### PR TITLE
Render variables in entire config not only alias

### LINKED ISSUE #3: Template variables in options.vars
Wondering if it wouldn't be a good idea to make this:

`const aliasURL = mustache.render(options.alias, process.env);`

work for the options.vars as well and not only alias, so it's possible to do something like:

```
default:
    options:
        vars:
            EMAIL_PREFIX: '{{CIRCLE_BRANCH}}'
```

### PR DESCRIPTION
**Pull request by vnenkpet**
Notes:
- I've moved the logic into the `commands/deploy.js` command code instead of the `deployers/now.js` code because it makes more sense to me (didn't see how is it relevant only to **now**)

fixes #3

### CODE REVIEW

**Comment by arturmuller** [comment]
Hey Petr. Thanks for the PR!

I see how it might feel at this point that it could be in either   in the launchkit core or the deployer, but I think the more correct separation of concerns is to have it in the deployer.

If we're ever open-sourcing this, it would feel weird to me that the core of the library does this extra, opinionated thing that's neither directly related to deployment nor to env var management.

Putting this in the core would mean that we're sure that *every single deployer* needs this functionality, which I don't think is true.

Can you please move these changes back to the **now** deployer?

**Comment by arturmuller** [comment]
Also, please update the README to include this new functionality.

**Comment by vnenkpet** [comment]
I can do that but I actually fail to see how is it connected to the *now* deployer itself. Seems to me pretty opinionated already that it replaces variables in the config with env vars using mustache without asking, I think it should at least be an option that can be turned off/on... in which case it against makes more sense to have it as a general option IMO

**Comment by arturmuller** [comment]
Ok, but you agree that it is opinionated, right?

As far as I know, tools with plugin-based architecture (Babel, ESLint, etc...) always try to keep the core as lean as possible so that they don't have to keep some obscure, rarely used feature in the core just for backwards compatibility.

Experimenting inside plugins is _safe_ because it is modularized. Adding stuff to core is scary because you might get stuck with it forever.

As I mentioned — are you sure that every single deployer would need templating? If so, would they need `mustache` specifically? How would they use a different templating language?

I think part of the reason it seems totally OK to me to be opinionated inside the `now` deployer is that I don't think of it as a generic `now` deployer. It is **our** `now` deployer, trailered for our specific needs and use-cases.

**Comment by arturmuller** [comment]
@vnenkpet any updates on this?

**Comment by vnenkpet** [comment]
Closing in favor of https://github.com/luskhq/launchkit/pull/8

**Pull request closed without merging**
